In [1]:
from jupyter_innotater import *
import numpy as np, os


In [15]:
# get images
# need to change the directory

images = sorted(os.listdir('./train/test'))

# number of labels (repeating labeling)
repeats = 6

targets_exclude = np.zeros((len(images), 1), dtype='int') # Binary flag to indicate want to exclude from dataset

# make objects to label
joints = ['LF-mtp-ip', 'LF-mtp-1', 'LF-mtp-2', 'LF-mtp-3', 'LF-mtp-4', 'LF-mtp-5']

# It's empty datasets here as a demo but should be pre-labeled dataset in the real trial
targets_joint = np.zeros((len(images), len(joints)), dtype='int')
targets_bboxes = np.zeros((len(images), repeats, 4), dtype='int') # (x,y,w,h) for each joint

Innotater(
    [
        ImageInnotation(images, path='./train/test', width=1275, height=1600), # Display the image itself
        TextInnotation(images, multiline=False) # Display the image filename
    ],
    [
        BinaryClassInnotation(targets_exclude, name='Exclude'), # Checkbox
        RepeatInnotation(
            (BoundingBoxInnotation, targets_bboxes), # Individual joint bounding box
            (MultiClassInnotation, targets_joint,
                {'name':'Joint', 'classes':joints, 'dropdown':True}), # Per image joint dropdown
            max_repeats=repeats, min_repeats=1
        )
    ]
)

Innotater(children=(HBox(children=(VBox(children=(ImagePad(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x0…

In [17]:
# primary labeling : this will be done my trained model in real trial
targets_bboxes

array([[[720, 198, 211, 188],
        [747, 489, 264, 212],
        [601, 464, 161, 172],
        [498, 516, 133, 147],
        [377, 580, 138, 172],
        [223, 695, 159, 171]],

       [[224, 537, 112, 105],
        [319, 475, 142, 145],
        [588, 484, 166, 154],
        [328, 479, 128, 122],
        [229, 538, 107, 101],
        [436, 452, 122, 125]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]])

In [18]:
# primitive labels as existing labels
existing_boxes = targets_bboxes
print(existing_boxes)

[[[720 198 211 188]
  [747 489 264 212]
  [601 464 161 172]
  [498 516 133 147]
  [377 580 138 172]
  [223 695 159 171]]

 [[224 537 112 105]
  [319 475 142 145]
  [588 484 166 154]
  [328 479 128 122]
  [229 538 107 101]
  [436 452 122 125]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]]


In [21]:
existing_joint = targets_joint
existing_joint

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0, 0]])

In [23]:
# Now start adjusting

images = sorted(os.listdir('./train/test'))

repeats = 6

targets_exclude = np.zeros((len(images), 1), dtype='int') # Binary flag to indicate want to exclude from dataset

joints = ['LF-mtp-ip', 'LF-mtp-1', 'LF-mtp-2', 'LF-mtp-3', 'LF-mtp-4', 'LF-mtp-5']

# Now inputs are existing labels
targets_joint = existing_joint
targets_bboxes = existing_boxes # (x,y,w,h) for each joint

# adjust the labels by running below code & manually re-draw the box
Innotater(
    [
        ImageInnotation(images, path='./train/test', width=1275, height=1600), # Display the image itself
        TextInnotation(images, multiline=False) # Display the image filename
    ],
    [
        BinaryClassInnotation(targets_exclude, name='Exclude'), # Checkbox
        RepeatInnotation(
            (BoundingBoxInnotation, targets_bboxes), # Individual joint bounding box
            (MultiClassInnotation, targets_joint,
                {'name':'Joint', 'classes':joints, 'dropdown':True}), # Per image joint dropdown
            max_repeats=repeats, min_repeats=1
        )
    ]
)

Innotater(children=(HBox(children=(VBox(children=(ImagePad(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x0…

In [26]:
# updated boxes

updated_boxes = targets_bboxes
targets_bboxes

array([[[719, 190, 216, 203],
        [746, 478, 236, 226],
        [601, 464, 161, 172],
        [498, 516, 133, 147],
        [377, 580, 138, 172],
        [223, 695, 159, 171]],

       [[224, 537, 112, 105],
        [319, 475, 142, 145],
        [588, 484, 166, 154],
        [328, 479, 128, 122],
        [229, 538, 107, 101],
        [436, 452, 122, 125]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]])